# Generated by Django 5.1.4 on 2024-12-07 20:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary_dash', '0002_medicine_alter_secretary_options_examination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='dosage_instructions',
            new_name='side_effects',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(default='obunga'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examination',
            name='date',
            field=models.DateField(),
        ),
    ]
