# Generated by Django 5.1.4 on 2024-12-07 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary_dash', '0003_rename_dosage_instructions_medicine_side_effects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
