# Generated by Django 5.1.4 on 2024-12-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary_dash', '0004_medicine_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterModelOptions(
            name='examination',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='examination',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
