# Generated by Django 5.1.4 on 2024-12-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary_dash', '0006_examination_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusyHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Busy Hours',
                'verbose_name_plural': 'Busy Hours',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
