# Generated by Django 5.1.4 on 2024-12-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary_dash', '0007_busyhours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busyhours',
            name='reason',
            field=models.CharField(max_length=200),
        ),
    ]
