# Generated by Django 5.1.4 on 2024-12-22 00:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary_dash', '0008_alter_busyhours_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='examination',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examination',
            name='date',
            field=models.DateField(),
        ),
    ]
