# Generated by Django 5.1.4 on 2024-12-22 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretary_dash', '0011_alter_prescription_examination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_cancelled',
        ),
    ]
